### ISSUE TITLE
“Socratic dialog”

### ISSUE THREAD

**Issue by fasiha** [eddieantonio/blog#2]
Hi Eddie thanks for writing https://eddieantonio.ca/blog/2023/10/25/python-is-a-compiled-language! I’m sending it to student friends but one thing gave me pause and I’m explaining it to them to avoid tripping them up: the Socratic dialogue is brilliant but making between “teacher” and “student” makes it a bit confusing because obviously this “teacher” is ignorant and the student is perceptive. I almost wonder if the labels can be switched, teacher→“misguided” and student→”Socrates” or something like that to indicate that the student is asking probing questions that show holes in the “teacher’s” mental model? 

Just a very small suggestion! Thanks for writing!!!

**Comment by eddieantonio** [comment]
Yes, I will admit that I am not happy with the names I gave my two interlocutors there. I settled on "teacher" and "student" but did not want anything that is outright insulting to anyone. I will mull this over the night and maybe come with better names tomorrow!

**Comment by eddieantonio** [comment]
Duh doy! The answer was staring me in the face! I replaced student/teacher with Socrates/Plato! Not super sure if my framing is faithful to their respective philosophies, but at least I'm not naming specific people.

Hopefully this seems like an appropriate change!

**Comment by fasiha** [comment]
Well done! In my mind Plato being the student that admired his teacher, and Socrates being the one who asked questions to expose people’s misunderstandings, I might have flipped the two but this is nice! Thanks!
